### PR TITLE
with this changes the packagebrowser compiles in windows enviroment too.

### PR DESCRIPTION
**Pull request by hkollmann**

### CODE REVIEW

**Review by cboulanger — COMMENTED** [review]
Thanks for this - did you replace the mkdirp function with a module because of windows?
Did you test that stderr was properly caught? I had troubles with spawn and stderr before...

**Comment by hkollmann** [comment]
yes, mkdirp works in Windows too.
I could catch the stderr - the trick was the shell option.
Tried in bash too.

**Review by cboulanger — APPROVED** [review]

**Comment by cboulanger** [comment]
Ah - the shell option - clever! I didn't get that!

**Comment by cboulanger** [comment]
Merging, thank you @hkollmann !

**Pull request merged**
